workflow updated

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -20,23 +20,41 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout code
+      uses: actions/checkout@v4
+
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
+
     - name: Install Google Chrome Driver
       run: |
-        sudo apt-get install chromium-chromedriver
+        sudo apt-get update
+        sudo apt-get install -y wget curl unzip
+        sudo apt-get install -y libnss3 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxi6 libxrandr2 libgbm1 libasound2 libu2f-udev
+        sudo apt-get install -y libicu70
+        
+        # Download and install Google Chrome for Testing
+        export CHROME_VERSION=131.0.6778.204
+        curl -sSL https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chrome-headless-shell-linux64.zip -o chrome-headless-shell-linux64.zip
+        unzip chrome-headless-shell-linux64.zip
+        
+        # Move the 'chrome-headless-shell' binary to /usr/bin
+        if [ -f "chrome-headless-shell-linux64/chrome-headless-shell" ]; then
+          sudo mv chrome-headless-shell-linux64/chrome-headless-shell /usr/bin/google-chrome
+        else
+          echo "Chrome binary not found in the expected location."
+          exit 1
+        fi
+        
+        # Verify installation
+        google-chrome --version
       
     - name: Run API jar
       run: java -jar ./api-testing/src/test/resources/libs/demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
         
     - name: Run Test Automation with Maven
       run: mvn clean verify
-
-    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
-    - name: Update dependency graph
-      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
